spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: service
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true